apiVersion: v1
kind: Service
metadata:
  name: photo-gallery
spec:
  type: NodePort
  selector:
    app: photo-gallery
  ports:
    - protocol: TCP
      port: 50080
      targetPort: 5000
      nodePort: 30080